export const aboutFeatures = [
    {
        title: "Talent & Workforce Acceleration",
        desc: "From literacy campaigns to certified blockchain developer programs to building a ready-to-hire national talent pipeline"
    },
    {
        title: "National Ecosystem Convergence",
        desc: "A multi-sector platform uniting universities, startups,VCs, enterprises, regulators, and Web3 communities across Indonesia’s."
    },
    {
        title: "Policy Alignment",
        desc: "Closed-door roundtables and cross-sector MoUs shaping practical blockchain policy and real-world adoption."
    }
]

export const galleryItems = Array.from({ length: 23 }, (_, i) => ({
    id: i + 1,
    title: 'Dummy',
    image: `/gallery/img${i + 1}.webp`,
}));

export const getInvolvedCard = [
    {
        id: 2,
        title: "Become A Sponsor",
        description: "Scale your brand visibility with a premium audience.",
        image: "/gallery/img12.webp",
        className: "md:col-span-1 md:row-span-1",
        href: '/sponsorship',

    },
    {
        id: 3,
        title: "Partner as Media",
        description: "Access exclusive press materials and cover groundbreaking news.",

        image: "/gallery/img20.webp",
        className: "md:col-span-1 md:row-span-2",
        href: '/media',

    },
    {
        id: 4,
        title: "Become an Affiliate",
        description: "Promote the world's top event and earn high-tier commissions.",
        image: "/gallery/img9.webp",
        className: "md:col-span-1 md:row-span-1",
        href: '/affiliate',

    },
];

export const countries = [
    { code: "AF", name: "Afghanistan" },
    { code: "AL", name: "Albania" },
    { code: "DZ", name: "Algeria" },
    { code: "AD", name: "Andorra" },
    { code: "AO", name: "Angola" },
    { code: "AG", name: "Antigua and Barbuda" },
    { code: "AR", name: "Argentina" },
    { code: "AM", name: "Armenia" },
    { code: "AU", name: "Australia" },
    { code: "AT", name: "Austria" },
    { code: "AZ", name: "Azerbaijan" },
    { code: "BS", name: "Bahamas" },
    { code: "BH", name: "Bahrain" },
    { code: "BD", name: "Bangladesh" },
    { code: "BB", name: "Barbados" },
    { code: "BY", name: "Belarus" },
    { code: "BE", name: "Belgium" },
    { code: "BZ", name: "Belize" },
    { code: "BJ", name: "Benin" },
    { code: "BT", name: "Bhutan" },
    { code: "BO", name: "Bolivia" },
    { code: "BA", name: "Bosnia and Herzegovina" },
    { code: "BW", name: "Botswana" },
    { code: "BR", name: "Brazil" },
    { code: "BN", name: "Brunei" },
    { code: "BG", name: "Bulgaria" },
    { code: "BF", name: "Burkina Faso" },
    { code: "BI", name: "Burundi" },
    { code: "CV", name: "Cabo Verde" },
    { code: "KH", name: "Cambodia" },
    { code: "CM", name: "Cameroon" },
    { code: "CA", name: "Canada" },
    { code: "CF", name: "Central African Republic" },
    { code: "TD", name: "Chad" },
    { code: "CL", name: "Chile" },
    { code: "CN", name: "China" },
    { code: "CO", name: "Colombia" },
    { code: "KM", name: "Comoros" },
    { code: "CG", name: "Congo" },
    { code: "CR", name: "Costa Rica" },
    { code: "HR", name: "Croatia" },
    { code: "CU", name: "Cuba" },
    { code: "CY", name: "Cyprus" },
    { code: "CZ", name: "Czech Republic" },
    { code: "DK", name: "Denmark" },
    { code: "DJ", name: "Djibouti" },
    { code: "DM", name: "Dominica" },
    { code: "DO", name: "Dominican Republic" },
    { code: "EC", name: "Ecuador" },
    { code: "EG", name: "Egypt" },
    { code: "SV", name: "El Salvador" },
    { code: "GQ", name: "Equatorial Guinea" },
    { code: "ER", name: "Eritrea" },
    { code: "EE", name: "Estonia" },
    { code: "SZ", name: "Eswatini" },
    { code: "ET", name: "Ethiopia" },
    { code: "FJ", name: "Fiji" },
    { code: "FI", name: "Finland" },
    { code: "FR", name: "France" },
    { code: "GA", name: "Gabon" },
    { code: "GM", name: "Gambia" },
    { code: "GE", name: "Georgia" },
    { code: "DE", name: "Germany" },
    { code: "GH", name: "Ghana" },
    { code: "GR", name: "Greece" },
    { code: "GD", name: "Grenada" },
    { code: "GT", name: "Guatemala" },
    { code: "GN", name: "Guinea" },
    { code: "GW", name: "Guinea-Bissau" },
    { code: "GY", name: "Guyana" },
    { code: "HT", name: "Haiti" },
    { code: "HN", name: "Honduras" },
    { code: "HU", name: "Hungary" },
    { code: "IS", name: "Iceland" },
    { code: "IN", name: "India" },
    { code: "ID", name: "Indonesia" },
    { code: "IR", name: "Iran" },
    { code: "IQ", name: "Iraq" },
    { code: "IE", name: "Ireland" },
    { code: "IL", name: "Israel" },
    { code: "IT", name: "Italy" },
    { code: "JM", name: "Jamaica" },
    { code: "JP", name: "Japan" },
    { code: "JO", name: "Jordan" },
    { code: "KZ", name: "Kazakhstan" },
    { code: "KE", name: "Kenya" },
    { code: "KI", name: "Kiribati" },
    { code: "KW", name: "Kuwait" },
    { code: "KG", name: "Kyrgyzstan" },
    { code: "LA", name: "Laos" },
    { code: "LV", name: "Latvia" },
    { code: "LB", name: "Lebanon" },
    { code: "LS", name: "Lesotho" },
    { code: "LR", name: "Liberia" },
    { code: "LY", name: "Libya" },
    { code: "LI", name: "Liechtenstein" },
    { code: "LT", name: "Lithuania" },
    { code: "LU", name: "Luxembourg" },
    { code: "MG", name: "Madagascar" },
    { code: "MW", name: "Malawi" },
    { code: "MY", name: "Malaysia" },
    { code: "MV", name: "Maldives" },
    { code: "ML", name: "Mali" },
    { code: "MT", name: "Malta" },
    { code: "MH", name: "Marshall Islands" },
    { code: "MR", name: "Mauritania" },
    { code: "MU", name: "Mauritius" },
    { code: "MX", name: "Mexico" },
    { code: "FM", name: "Micronesia" },
    { code: "MD", name: "Moldova" },
    { code: "MC", name: "Monaco" },
    { code: "MN", name: "Mongolia" },
    { code: "ME", name: "Montenegro" },
    { code: "MA", name: "Morocco" },
    { code: "MZ", name: "Mozambique" },
    { code: "MM", name: "Myanmar" },
    { code: "NA", name: "Namibia" },
    { code: "NR", name: "Nauru" },
    { code: "NP", name: "Nepal" },
    { code: "NL", name: "Netherlands" },
    { code: "NZ", name: "New Zealand" },
    { code: "NI", name: "Nicaragua" },
    { code: "NE", name: "Niger" },
    { code: "NG", name: "Nigeria" },
    { code: "NO", name: "Norway" },
    { code: "OM", name: "Oman" },
    { code: "PK", name: "Pakistan" },
    { code: "PW", name: "Palau" },
    { code: "PA", name: "Panama" },
    { code: "PG", name: "Papua New Guinea" },
    { code: "PY", name: "Paraguay" },
    { code: "PE", name: "Peru" },
    { code: "PH", name: "Philippines" },
    { code: "PL", name: "Poland" },
    { code: "PT", name: "Portugal" },
    { code: "QA", name: "Qatar" },
    { code: "RO", name: "Romania" },
    { code: "RU", name: "Russia" },
    { code: "RW", name: "Rwanda" },
    { code: "KN", name: "Saint Kitts and Nevis" },
    { code: "LC", name: "Saint Lucia" },
    { code: "VC", name: "Saint Vincent and the Grenadines" },
    { code: "WS", name: "Samoa" },
    { code: "SM", name: "San Marino" },
    { code: "ST", name: "Sao Tome and Principe" },
    { code: "SA", name: "Saudi Arabia" },
    { code: "SN", name: "Senegal" },
    { code: "RS", name: "Serbia" },
    { code: "SC", name: "Seychelles" },
    { code: "SL", name: "Sierra Leone" },
    { code: "SG", name: "Singapore" },
    { code: "SK", name: "Slovakia" },
    { code: "SI", name: "Slovenia" },
    { code: "SB", name: "Solomon Islands" },
    { code: "SO", name: "Somalia" },
    { code: "ZA", name: "South Africa" },
    { code: "SS", name: "South Sudan" },
    { code: "ES", name: "Spain" },
    { code: "LK", name: "Sri Lanka" },
    { code: "SD", name: "Sudan" },
    { code: "SR", name: "Suriname" },
    { code: "SE", name: "Sweden" },
    { code: "CH", name: "Switzerland" },
    { code: "SY", name: "Syria" },
    { code: "TW", name: "Taiwan" },
    { code: "TJ", name: "Tajikistan" },
    { code: "TZ", name: "Tanzania" },
    { code: "TH", name: "Thailand" },
    { code: "TL", name: "Timor-Leste" },
    { code: "TG", name: "Togo" },
    { code: "TO", name: "Tonga" },
    { code: "TT", name: "Trinidad and Tobago" },
    { code: "TN", name: "Tunisia" },
    { code: "TR", name: "Turkey" },
    { code: "TM", name: "Turkmenistan" },
    { code: "TV", name: "Tuvalu" },
    { code: "UG", name: "Uganda" },
    { code: "UA", name: "Ukraine" },
    { code: "AE", name: "United Arab Emirates" },
    { code: "GB", name: "United Kingdom" },
    { code: "US", name: "United States" },
    { code: "UY", name: "Uruguay" },
    { code: "UZ", name: "Uzbekistan" },
    { code: "VU", name: "Vanuatu" },
    { code: "VE", name: "Venezuela" },
    { code: "VN", name: "Vietnam" },
    { code: "YE", name: "Yemen" },
    { code: "ZM", name: "Zambia" },
    { code: "ZW", name: "Zimbabwe" },
];



export const faqData = [
    {
        category: "General",
        questions: [
            { q: "What is Bali Blockchain Weeks?", a: "Bali Blockchain Weeks 2026 is a multi-pillar program aimed at strengthening blockchain adoption in Indonesia and positioning the country as the Web3 Hub of Southeast Asia" },
            { q: "When will the event take place?", a: "The main event takes place on May 9, 2026" },
            { q: "Is the event open for beginners?", a: "Absolutely. It brings together students, developers, professionals, government regulators, and enterprise leaders" },
            { q: "What is the overall impact target for Bali Blockchain Weeks", a: "The program aims to drastically build the local ecosystem by producing over 1,500 ready-to-hire certified developers and incubating 50+ new startups." },
        ]
    },
    {
        category: "Tickets",
        questions: [
            { q: "How can I purchase tickets?", a: "Tickets can be purchased directly through our website in ticketing section" },
            { q: "What types of tickets are available?", a: "standard Conference Passes and VIP Networking Passes." },
        ]
    },
    {
        category: "Sponsorship & Marketing",
        questions: [
            { q: "Do sponsors get speaking opportunities?", a: "Yes, all tiers include main stage speaking slots. The Co-Host package includes 2 Keynote slots, 2 Panel Discussion slots, and a priority speaking role during the Opening Ceremony." },
            { q: "Are there custom marketing packages?", a: "Yes, our team can tailor a package that fits your specific brand goals and target audience during the event" },
        ]
    },
    {
        category: "Program & Agenda",
        questions: [
            { q: "What are the main pillars of the Bali Blockchain Weeks program?", a: "The program is built on three integrated pillars: Literacy (a National Campus Roadshow), Training (a Developer & Workforce Program), and the culminating National Conference." },
            { q: "What will the technical training track cover for developers?", a: "The technical track focuses heavily on dApp development—including full-stack decentralized application building using Solidity/Rust, Web3.js integration, and frontend connectivity—alongside smart contract security topics like auditing basics and secure coding standards." },
        ]
    },
    {
        category: "Partnerships",
        questions: [
            { q: "How do I apply as a Community Partner?", a: "We love collaborating with local and global communities. Fill out the partnership form on our website to get started." },
            { q: "Are there opportunities to partner with local educational institutions?", a: "Yes, the National Campus Roadshow pillar is specifically designed to partner with 10+ campuses across the region to deliver literacy seminars, socialize policy, and map potential developer talent" },
        ]
    }
];


export const plans = [
    {
        id: "0",
        title: "General Pass",
        price: 50,
        caption: "Entry level access",
        features: [
            "Entrance ticket",
            "F & B",
            "Conference zone",
            "Exibition zone",
        ],
        logo: "/logo.png",
    },
    {
        id: "1",
        title: "VIP Pass",
        price: 500,
        caption: "Maximum exclusivity",
        features: [
            "Fast lane registration",
            "All benefit general pass",
            "VIP ZONE",
            "VIP Networking",
            "Dedicate concierge",
        ],
        logo: "/logo.png",
    },
    {
        id: "2",
        title: "General Pass",
        price: 50,
        caption: "Entry level access",
        features: [
            "Entrance ticket",
            "F & B",
            "Conference zone",
            "Exibition zone",
        ],
        logo: "/logo.png",
    },
];